version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Django"
        versions: [">=6.0.0"]
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tailwindcss"
        versions: [">=4.0.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
