import os
from db import get_db, is_postgres
from datetime import datetime
from zoneinfo import ZoneInfo


def _get_targets(conn):
    cur = conn.execute("SELECT DISTINCT target_username FROM runs ORDER BY target_username")
    return [row[0] for row in cur.fetchall()]


def _get_latest_run(conn, target_username):
    cur = conn.execute(
        """
        SELECT id, timestamp, followers_count, followees_count, non_followbacks_count,
               followers_added, followers_removed, followees_added, followees_removed
        FROM runs
        WHERE target_username = ?
        ORDER BY timestamp DESC, id DESC
        LIMIT 1
        """,
        (target_username,),
    )
    row = cur.fetchone()
    if not row:
        return None
    return {
        "run_id": row[0],
        "timestamp": row[1],
        "followers_count": row[2],
        "followees_count": row[3],
        "non_followbacks_count": row[4],
        "followers_added": row[5],
        "followers_removed": row[6],
        "followees_added": row[7],
        "followees_removed": row[8],
    }


def _get_history(conn, target_username, limit=10):
    cur = conn.execute(
        """
        SELECT timestamp, followers_count, followees_count, non_followbacks_count,
               followers_added, followers_removed, followees_added, followees_removed
        FROM runs
        WHERE target_username = ?
        ORDER BY timestamp DESC, id DESC
        LIMIT ?
        """,
        (target_username, limit),
    )
    rows = []
    for row in cur.fetchall():
        rows.append(
            {
                "timestamp": row[0],
                "followers_count": row[1],
                "followees_count": row[2],
                "non_followbacks_count": row[3],
                "followers_added": row[4],
                "followers_removed": row[5],
                "followees_added": row[6],
                "followees_removed": row[7],
            }
        )
    return rows


def _friendly_schedule(cron_expr):
    # expected patterns generated by builder
    parts = cron_expr.split()
    if len(parts) != 5:
        return cron_expr
    m, h, dom, mon, dow = parts
    def fmt(hh, mm): return f"{int(hh):02d}:{int(mm):02d} ET"
    if dom == "*" and dow == "*" and "," not in m and "," not in h:
        return f"Daily at {fmt(h, m)}"
    if dom == "*" and dow == "*" and "," in m and "," in h:
        ms = m.split(","); hs = h.split(",")
        if len(ms) == 2 and len(hs) == 2:
            return f"Twice daily at {fmt(hs[0], ms[0])} & {fmt(hs[1], ms[1])}"
    if dom == "*/2":
        return f"Every other day at {fmt(h, m)}"
    if dow != "*" and dom == "*":
        days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]
        dname = days[int(dow)] if dow.isdigit() and int(dow) < 7 else dow
        return f"{dname} at {fmt(h, m)}"
    return cron_expr


TZ = ZoneInfo("America/New_York")


def fmt_ts(ts):
    if not ts:
        return "n/a"
    try:
        if "_" in ts and len(ts) == 19:  # %Y-%m-%d_%H-%M-%S
            dt = datetime.strptime(ts, "%Y-%m-%d_%H-%M-%S").replace(tzinfo=TZ)
        elif " " in ts:
            try:
                dt = datetime.strptime(ts, "%Y-%m-%d %H:%M:%S %Z").astimezone(TZ)
            except ValueError:
                dt = datetime.strptime(ts, "%Y-%m-%d %H:%M:%S").replace(tzinfo=TZ)
        else:
            dt = datetime.fromisoformat(ts)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=TZ)
            else:
                dt = dt.astimezone(TZ)
        return dt.strftime("%b %d, %-I:%M %p ET")
    except Exception:
        return ts


def _get_run_usernames(conn, run_id):
    followers = [r[0] for r in conn.execute("SELECT username FROM run_followers WHERE run_id = ? ORDER BY username", (run_id,))]
    followees = [r[0] for r in conn.execute("SELECT username FROM run_followees WHERE run_id = ? ORDER BY username", (run_id,))]
    return followers, followees


def _compute_diff(conn, target_username):
    """Return latest run info with added/removed lists and non-followbacks usernames."""
    latest = _get_latest_run(conn, target_username)
    if not latest:
        return None
    latest_followers, latest_followees = _get_run_usernames(conn, latest["run_id"])

    # find previous run (second most recent)
    cur = conn.execute(
        """
        SELECT id FROM runs
        WHERE target_username = ?
        ORDER BY timestamp DESC, id DESC
        LIMIT 1 OFFSET 1
        """,
        (target_username,),
    )
    prev_row = cur.fetchone()
    prev_followers = prev_followees = []
    if prev_row:
        prev_followers, prev_followees = _get_run_usernames(conn, prev_row[0])

    prev_f_set = set(prev_followers)
    prev_fe_set = set(prev_followees)
    latest_f_set = set(latest_followers)
    latest_fe_set = set(latest_followees)

    diff = {
        "latest": latest,
        "followers_added_list": sorted(latest_f_set - prev_f_set),
        "followers_removed_list": sorted(prev_f_set - latest_f_set),
        "followees_added_list": sorted(latest_fe_set - prev_fe_set),
        "followees_removed_list": sorted(prev_fe_set - latest_fe_set),
        "non_followbacks_list": sorted(latest_fe_set - latest_f_set),
        "followers_list": latest_followers,
        "followees_list": latest_followees,
        "runs_count": conn.execute(
            "SELECT COUNT(*) FROM runs WHERE target_username = ?", (target_username,)
        ).fetchone()[0],
        "delta_followers": latest["followers_count"] - (len(prev_followers) if prev_followers else 0),
        "delta_followees": latest["followees_count"] - (len(prev_followees) if prev_followees else 0),
    }
    return diff


def _sparkline_svg(values, width=140, height=40, stroke="#2563eb"):
    if not values:
        return ""
    # limit to last 30 points to keep SVG light
    values = values[-30:]
    n = len(values)
    if n == 1:
        values = values * 2
        n = 2
    min_v = min(values)
    max_v = max(values)
    span = max(max_v - min_v, 1)
    xs = [i * (width / (n - 1)) for i in range(n)]
    ys = [height - ((v - min_v) / span) * (height - 6) - 3 for v in values]
    points = " ".join(f"{x:.1f},{y:.1f}" for x, y in zip(xs, ys))
    return f'<svg viewBox="0 0 {width} {height}" preserveAspectRatio="none" width="100%" height="40"><polyline fill="none" stroke="{stroke}" stroke-width="2" points="{points}" /></svg>'


def _render_target_card(target_username, latest, diff, spark):
    name = target_username
    ts = latest.get("timestamp", "unknown")
    followers = latest.get("followers_count", 0)
    followees = latest.get("followees_count", 0)
    non_followbacks = latest.get("non_followbacks_count")
    delta_f = diff.get("delta_followers", 0) if diff else 0
    delta_fe = diff.get("delta_followees", 0) if diff else 0
    delta_badge = f"+{delta_f}" if delta_f >= 0 else f"{delta_f}"
    delta_badge_fe = f"+{delta_fe}" if delta_fe >= 0 else f"{delta_fe}"

    return f"""
      <section class="card">
        <div class="card-head">
          <div>
            <h2>@{name}</h2>
            <p class="muted">Latest run: {fmt_ts(ts)}</p>
          </div>
          <span class="pill">Updated {fmt_ts(ts)}</span>
        </div>
        <div class="metrics">
          <div>
            <p class="label">Followers</p>
            <p class="value">{followers}</p>
            <p class="delta">{delta_badge}</p>
          </div>
          <div>
            <p class="label">Following</p>
            <p class="value">{followees}</p>
            <p class="delta">{delta_badge_fe}</p>
          </div>
          <div>
            <p class="label">Non-followbacks</p>
            <p class="value">{non_followbacks if non_followbacks is not None else "n/a"}</p>
          </div>
        </div>
        <div class="spark">{spark}</div>
      </section>
    """


def _render_history_table(history, name):
    if not history:
        return f"""
        <div class="empty">No history yet for @{name}. Run the script a few times to populate trends.</div>
        """

    rows = []
    for item in history:
        rows.append(
            f"""
            <tr>
              <td>{fmt_ts(item.get('timestamp', ''))}</td>
              <td>{item.get('followers_count', 0)}</td>
              <td>{item.get('followees_count', 0)}</td>
              <td>{item.get('followers_added', 0)}</td>
              <td>{item.get('followers_removed', 0)}</td>
            </tr>
            """
        )
    rows_html = "\n".join(rows)
    return f"""
      <table>
        <thead>
          <tr>
            <th>Timestamp</th>
            <th>Followers</th>
            <th>Following</th>
            <th>New Followers</th>
            <th>Lost Followers</th>
          </tr>
        </thead>
        <tbody>
          {rows_html}
        </tbody>
      </table>
    """


def build_dashboard(base_dir, output_path, db_path):
    tz = TZ
    if not is_postgres():
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
    conn = get_db()
    try:
        # Summary stats
        cur = conn.execute("SELECT COUNT(*) FROM runs")
        total_runs = cur.fetchone()[0] if cur else 0
        targets_list = _get_targets(conn)
        total_targets = len(targets_list)

        targets = _get_targets(conn)
        target_rows = []
        for target in targets:
            latest = _get_latest_run(conn, target)
            history = _get_history(conn, target)
            if not latest:
                continue
            diff = _compute_diff(conn, target)
            history_counts = [h["followers_count"] for h in reversed(history)]
            spark = _sparkline_svg(history_counts)
            target_rows.append({"target": target, "latest": latest, "history": history, "diff": diff, "spark": spark})
    finally:
        conn.close()

    generated = datetime.now(tz).strftime("%b %d, %I:%M %p ET")

    cards_html = "\n".join(
        [_render_target_card(t["target"], t["latest"], t["diff"], t["spark"]) for t in target_rows]
    ) or "<p>No targets found.</p>"

    # Build details sections with lists and diffs
    details_sections = []
    for t in target_rows:
        diff = t["diff"]
        if not diff:
            continue
        def _ul(items):
            if not items:
                return "<p class='muted'>None</p>"
            return "<ul class='list'>" + "".join(f"<li>{x}</li>" for x in items) + "</ul>"

        details_sections.append(
            f"""
            <section class="detail">
              <div class="detail-head">
                <div>
                  <h3>@{t['target']} latest snapshot</h3>
                  <p class="muted">Run {diff['latest']['run_id']} · {fmt_ts(diff['latest']['timestamp'])}</p>
                </div>
                <div class="actions">
                  <button class="ghost" onclick="downloadCSV('{t['target']}-followers.csv', {len(diff['followers_list'])}, followersData['{t['target']}'].followers)">Followers CSV</button>
                  <button class="ghost" onclick="downloadCSV('{t['target']}-following.csv', {len(diff['followees_list'])}, followersData['{t['target']}'].followees)">Following CSV</button>
                  <button class="ghost" onclick="downloadCSV('{t['target']}-nonfollowbacks.csv', {len(diff['non_followbacks_list'])}, followersData['{t['target']}'].non_followbacks)">Non-followbacks CSV</button>
                </div>
              </div>
              <div class="detail-grid">
                <div>
                  <h4>Followers added</h4>
                  {_ul(diff['followers_added_list'])}
                </div>
                <div>
                  <h4>Followers removed</h4>
                  {_ul(diff['followers_removed_list'])}
                </div>
                <div>
                  <h4>Following added</h4>
                  {_ul(diff['followees_added_list'])}
                </div>
                <div>
                  <h4>Following removed</h4>
                  {_ul(diff['followees_removed_list'])}
                </div>
                <div class="span2">
                  <h4>Non-followbacks (followed but not following back)</h4>
                  {_ul(diff['non_followbacks_list'])}
                </div>
              </div>
            </section>
            """
        )
    details_html = "\n".join(details_sections)

    histories = []
    for target in target_rows:
        name = target["target"]
        histories.append(
            f"""
            <section class="history">
              <h3>@{name} history</h3>
              {_render_history_table(target["history"], name)}
            </section>
            """
        )
    history_html = "\n".join(histories)

    followers_data = {
        t["target"]: {
            "followers": (t["diff"]["followers_list"] if t["diff"] else []),
            "followees": (t["diff"]["followees_list"] if t["diff"] else []),
            "non_followbacks": (t["diff"]["non_followbacks_list"] if t["diff"] else []),
        }
        for t in target_rows
    }

    html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Instaloader Dashboard</title>
    <style>
      :root {{
        --bg: #f7f8fb;
        --ink: #0f172a;
        --muted: #6b7280;
        --accent: #2563eb;
        --accent-2: #0ea5e9;
        --card: #ffffff;
        --shadow: 0 20px 60px rgba(15, 23, 42, 0.10);
        --radius: 18px;
      }}
      * {{ box-sizing: border-box; }}
      body {{
        margin: 0;
        font-family: "Space Grotesk", "Manrope", -apple-system, "Segoe UI", sans-serif;
        color: var(--ink);
        background: linear-gradient(145deg, #eef2ff 0%, #f7f8fb 45%, #f0f9ff 100%);
      }}
      header {{
        padding: 32px 6vw 12px;
      }}
      h1 {{
        font-size: clamp(28px, 4vw, 44px);
        margin: 0 0 6px;
        letter-spacing: -0.02em;
      }}
      .sub {{
        color: var(--muted);
        margin: 0;
      }}
      main {{ padding: 0 6vw 64px; }}
      .summary-grid {{
        display: grid;
        gap: 14px;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        margin: 12px 0 24px;
      }}
      .grid {{
        display: grid;
        gap: 18px;
        grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
        margin: 24px 0 34px;
      }}
      .card {{
        background: var(--card);
        border-radius: var(--radius);
        padding: 18px 20px;
        box-shadow: var(--shadow);
        border: 1px solid rgba(15, 23, 42, 0.04);
      }}
      .card.stat {{
        display: grid;
        gap: 6px;
      }}
      .hint {{ color: var(--muted); font-size: 12px; margin: 0; }}
      .card-head {{
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 12px;
      }}
      .spark {{ margin-top: 8px; }}
      .pill {{
        background: #1b1b1d;
        color: #fff;
        padding: 4px 10px;
        border-radius: 999px;
        font-size: 12px;
        letter-spacing: 0.04em;
        text-transform: uppercase;
      }}
      .muted {{ color: var(--muted); font-size: 14px; }}
      .metrics {{
        display: grid;
        grid-template-columns: repeat(3, minmax(0, 1fr));
        gap: 12px;
        margin: 16px 0;
      }}
      .label {{
        margin: 0;
        text-transform: uppercase;
        font-size: 11px;
        letter-spacing: 0.08em;
        color: var(--muted);
      }}
      .value {{
        margin: 6px 0 0;
        font-size: 22px;
        font-weight: 700;
      }}
      .delta {{
        margin: 4px 0 0;
        font-size: 12px;
        color: var(--accent);
      }}
      .links {{
        display: flex;
        gap: 14px;
        flex-wrap: wrap;
        font-size: 13px;
      }}
      a {{
        color: var(--accent-2);
        text-decoration: none;
        border-bottom: 1px solid transparent;
      }}
      a:hover {{
        border-bottom: 1px solid var(--accent-2);
      }}
      .history {{
        margin-top: 26px;
        padding: 16px 20px;
        background: #f8fafc;
        border-radius: var(--radius);
        border: 1px solid rgba(15, 23, 42, 0.04);
      }}
      .badge {{
        display: inline-block;
        padding: 4px 10px;
        border-radius: 999px;
        background: #e0f2fe;
        color: var(--ink);
        font-size: 12px;
      }}
      table {{
        width: 100%;
        border-collapse: collapse;
        font-size: 13px;
      }}
      th, td {{
        padding: 10px 8px;
        text-align: left;
        border-bottom: 1px solid #e6e1d7;
      }}
      th {{
        font-size: 11px;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        color: var(--muted);
      }}
      .empty {{
        color: var(--muted);
        font-size: 13px;
        padding: 12px 0;
      }}
      footer {{
        margin-top: 34px;
        color: var(--muted);
        font-size: 12px;
      }}
      .detail {{
        background: #ffffff;
        border-radius: var(--radius);
        padding: 16px 18px;
        box-shadow: var(--shadow);
        border: 1px solid rgba(15, 23, 42, 0.04);
        margin-top: 16px;
      }}
      .detail-head {{
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 12px;
        flex-wrap: wrap;
      }}
      .detail-grid {{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
        gap: 14px;
        margin-top: 14px;
      }}
      .list {{
        padding-left: 16px;
        margin: 8px 0 0;
        max-height: 220px;
        overflow: auto;
      }}
      .ghost {{
        background: #eef2ff;
        color: var(--ink);
        border-radius: 12px;
        padding: 8px 12px;
        border: 1px solid #e2e8f0;
        cursor: pointer;
      }}
      .summary-pill {{
        font-size: 13px;
        padding: 6px 10px;
        border-radius: 12px;
        background: #e0f2fe;
        color: #0f172a;
        display: inline-flex;
        align-items: center;
        gap: 6px;
      }}
      .stats-grid {{
        display: grid;
        gap: 12px;
        grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      }}
      @media (max-width: 720px) {{
        .metrics {{
          grid-template-columns: 1fr;
        }}
      }}
    </style>
  </head>
  <body>
    <header>
      <h1>Instaloader Dashboard</h1>
      <p class="sub">Snapshots across your tracked targets. Updated {generated}.</p>
    </header>
    <main>
      <div class="summary-grid">
        <div class="card stat">
          <p class="label">Targets tracked</p>
          <p class="value">{total_targets}</p>
          <p class="hint">Active profiles with snapshots</p>
        </div>
        <div class="card stat">
          <p class="label">Total runs</p>
          <p class="value">{total_runs}</p>
          <p class="hint">All snapshots stored</p>
        </div>
        <div class="card stat">
          <p class="label">Last generated</p>
          <p class="value" style="font-size:18px;">{generated}</p>
          <p class="hint">Eastern Time</p>
        </div>
      </div>
      <div class="grid">
        {cards_html}
      </div>
      {details_html}
      {history_html}
      <footer>Generated locally from run metadata in instaloader.db.</footer>
    </main>
    <script>
      const followersData = {followers_data};
      function downloadCSV(filename, count, arr) {{
        if (!arr || !arr.length) {{ alert('No data'); return; }}
        const csv = 'username\\n' + arr.join('\\n');
        const blob = new Blob([csv], {{type: 'text/csv'}});
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
      }}
    </script>
  </body>
</html>
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(html)


if __name__ == "__main__":
    base_dir = os.path.abspath(os.path.dirname(__file__))
    output_path = os.path.join(base_dir, "dashboard", "index.html")
    db_path = os.path.join(base_dir, "instaloader.db")
    build_dashboard(base_dir, output_path, db_path)
    print(f"Dashboard written to {output_path}")
